/*
 * SAM_Programming.h
 *
 *  Created on: 11.02.2019
 *      Author: dinkelsv64505
 */

#ifndef BLUEHOME_SOURCEACTIONMANAGER_SAM_PROGRAMMING_H_
#define BLUEHOME_SOURCEACTIONMANAGER_SAM_PROGRAMMING_H_

void sam_pr_notifyEvent();

#endif /* BLUEHOME_SOURCEACTIONMANAGER_SAM_PROGRAMMING_H_ */
